### ISSUE TITLE
Visualisation

### ISSUE THREAD

**Issue by nangosyah** [noamteyssier/crispr_screen#134]
Hello,

I'm trying to use this implementation to do some analysis on pooled KO-CRISPR experiment with 10 samples divided in two groups: control and treatment. For each sample I have the amount of guideRNA at T0 and at T12. I want to find which genes are differentially expressed.

Is there a way I can account for time in the model and also visualise the results from the work flow.

Thanks

**Comment by noamteyssier** [comment]
Hey @nangosyah 

Unfortunately I don't have a generalized linear model implemented for `crispr_screen` where you can account for multiple variables and their interactions. 

However, you can perhaps run [`DESeq2`](https://bioconductor.org/packages/release/bioc/html/DESeq2.html) or [`edgeR`](https://bioconductor.org/packages/release/bioc/html/edgeR.html) with your specific design for the differential abundance analysis and then use `crispr_screen agg` to aggregate the p-values at a gene level for the sgRNAs on your chosen contrast.

For visualization you can check out my tool [screenviz](https://github.com/noamteyssier/screenviz)
